### ISSUE TITLE
nerves_uart integration and more features

### ISSUE THREAD

**Issue by fhunleth** [kfatehi/firmata#1]
Hi Keyvan - for lack of a better way of contacting you, I was wondering what you're plans were for the firmata library. It's getting more use now and some forks are being created (see @mobileoverlord's fork especially.) It would be great to update the version on hex.pm. I don't know how much time that you want to put into this, so if you're done with it, it would good to find a new maintainer. However, it certainly would be great if you were interested in getting back to it.

**Comment by kfatehi** [comment]
Hi Frank (going to ping your name so that it increase likelyhood of you being notified @fhunleth ) -- I don't know why I didn't get a notification for this.... Sorry for being difficult to reach; I've been sort of rejecting all these proprietary messaging systems as of late, including Slack. I also have not had the opportunity to use nerves or even elixir, for some time.

I just checked @mobileoverlord's fork and it looks like he added nerves_uart as a dependency. I purposely did not make the serial communication part of the scope for this project, so one could use any means of communication. The package purposely only implements the protocol itself.. It makes sense that there was no pull request as a result.

Still, it looks like there were protocol-related improvements and im not sure why he did not PR those.

That said, it's true I'm not doing much elixir at the moment, but I can definitely review PR's and update hex.pm if anything comes in -- assuming github notifies me... I'll check on that and see what the problem was there.

If the above is not enough and you guys want control of the hex.pm name that's fine too, because I'm not even active in the community at this time.

**Comment by kfatehi** [comment]
@entone is now maintaining this repository and is an owner of `firmata` on hex.pm
